---
resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
    branch: master

- name: git-kubo-deployment
  type: git
  source:
    uri: https://github.com/iainsproat/kubo-deployment #TODO: https://github.com/cloudfoundry-incubator/kubo-deployment
    branch: master
    ignore_paths:
    - '*.md'
    - 'LICENSE'
    - 'NOTICE'

- name: git-kubo-release
  type: git
  source:
    uri: https://github.com/iainsproat/kubo-release #TODO: https://github.com/cloudfoundry-incubator/kubo-release
    branch: master
    ignore_paths:
    - '*.md'
    - 'LICENSE'
    - 'NOTICE'
    private_key: ((ci-final-ssh-key)) #has both public & private keys in credhub, how do we get just the private key?

# - name: gcs-kubo-releases
#   type: gcs
#   source:
#     json_key: ((gcs-json-key))
#     bucket: kubo-releases
#     regexp: kubo-release-(.*).tgz

# - name: gcs-kubo-deployments
#   type: gcs
#   source:
#     json_key: ((gcs-json-key))
#     bucket: kubo-releases
#     regexp: kubo-deployment-(.*).tgz

- name: gcs-kubo-release-tarball
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-public
    versioned_file: kubo-release-latest.tgz

# - name: gcs-kubo-deployment-tarball
#   type: gcs
#   source:
#     json_key: ((gcs-json-key))
#     bucket: kubo-public
#     versioned_file: kubo-deployment-latest-test-final.tgz

- name: kubo-version
  type: semver
  source:
    key: kubo-version
    access_key_id: ((gcs-access-key-id))
    secret_access_key: ((gcs-secret-access-key))
    bucket: kubo-release-blobs-test # TODO: kubo-pipeline-store
    region_name: europe-west1
    endpoint: storage.googleapis.com

#- name: kubo-release-github-commit
#  type: git
#  source:
#    uri: git@github.com:iainsproat/kubo-release.git #TODO: git@github.com:cloudfoundry-incubator/kubo-release.git
#    branch: master
#    private_key: ((ci-final-ssh-key)) #TODO this returns both public & private keys, need to get private key only...
#
#



#- name: kubo-release-github-release
#  type: github-release
#  source:
#    owner: iainsproat #TODO: cloudfoundry-incubator
#    repository: kubo-release
#    pre_release: true
#    drafts: true

jobs:
- name: finalize-kubo-release
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: kubo-version
      params:
        bump: final
    - get: git-kubo-release
    - get: gcs-kubo-release-tarball
  - task: finalize-release
    file: git-kubo-ci/tasks/finalize-kubo-release.yml
    params:
      ACCESS_KEY_ID: ((gcs-access-key-id))
      SECRET_ACCESS_KEY: ((gcs-secret-access-key))
  - task: push-final-build
    params:
      repository: git-kubo-release
  - put: kubo-version
    params:
      bump: patch

