platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/upgrade-stemcell-test-ha.sh
params:

inputs:
- name: git-kubo-ci
- name: git-kubo-deployment
- name: gcs-kubo-release-tarball
- name: kubo-lock
- name: gcs-bosh-state
- name: gcs-bosh-creds
- name: new-bosh-stemcell
outputs:
- name: bosh-state
- name: bosh-creds
