azs:
- name: z1
  cloud_properties: {availability_zone: ((az))}

vm_types:
- name: default
  cloud_properties:
    instance_type: t2.micro
    ephemeral_disk: {size: 3000, type: gp2}
- name: large
  cloud_properties:
    instance_type: m3.large
    ephemeral_disk: {size: 30000, type: gp2}
- name: workers
  cloud_properties:
    instance_type: m3.2xlarge
    ephemeral_disk: {size: 409600, type: gp2}

disk_types:
- name: default
  disk_size: 3000
  cloud_properties: {type: gp2}
- name: large
  disk_size: 50_000
  cloud_properties: {type: gp2}

networks:
- name: ((deployments_network))
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    az: z1
    dns: [8.8.8.8]
    reserved: ((reserved_ips))
    cloud_properties: {subnet: ((subnet_id))}
- name: vip
  type: vip

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: large
  network: ((deployments_network))
